# _config.yml (root)

title: NIH Awards Tracker
description: Contracts & awards explorer

url: "https://feldmangn.github.io"
baseurl: "/nih-awards-tracker"   # keep this for a project site

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

menu:
  - title: Home
    url: /

  - title: HHS
    url: /hhs/
    children:
      - title: NIH
        url: /hhs/nih/
      - title: ARPA-H
        url: /hhs/arpa-h/
      - title: AHRQ
        url: /hhs/ahrq/
      - title: CMS
        url: /hhs/cms/

  - title: DoD
    url: /dod/
    children:
      - title: Army
        url: /dod/army/
        children:
          - title: USAMRDC
            url: /dod/army/usamrdc/
          - title: USACE ERDC
            url: /dod/army/erdc/
      - title: Navy
        url: /dod/navy/
        children:
          - title: ONR
            url: /dod/navy/onr/
          - title: NAVWAR
            url: /dod/navy/navwar/
      - title: Air Force
        url: /dod/air-force/
        children:
          - title: AFRL
            url: /dod/air-force/afrl/
      - title: DHA
        url: /dod/dha/

  - title: DOE
    url: /doe/
    children:
      - title: Office of Science
        url: /doe/sc/
      - title: ARPA-E
        url: /doe/arpa-e/

  - title: EPA
    url: /epa/
