menu:
  - title: Home
    url: /

  # ===== HHS =====
  - title: HHS
    url: /hhs/
    menu:
      - title: NIH
        url: /hhs/nih/
      - title: ARPA-H
        url: /hhs/arpa-h/
      - title: AHRQ
        url: /hhs/ahrq/
      - title: CMS
        url: /hhs/cms/

  # ===== DoD =====
  - title: DoD
    url: /dod/
    menu:
      - title: Army
        url: /dod/army/
        menu:
          - title: USAMRDC
            url: /dod/army/usamrdc/
          - title: USACE ERDC
            url: /dod/army/erdc/
      - title: Navy
        url: /dod/navy/
        menu:
          - title: ONR
            url: /dod/navy/onr/
          - title: NAVWAR
            url: /dod/navy/navwar/
      - title: Air Force
        url: /dod/air-force/
        menu:
          - title: AFRL
            url: /dod/air-force/afrl/
      - title: DHA
        url: /dod/dha/

  # ===== DOE =====
  - title: DOE
    url: /doe/
    menu:
      - title: Office of Science
        url: /doe/sc/
      - title: ARPA-E
        url: /doe/arpa-e/

  # ===== EPA =====
  - title: EPA
    url: /epa/
