name: refresh-usaspending
on:
  schedule:
    - cron: "17 2 * * *"   # daily at 02:17 UTC
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pull USAspending (last 90 days)
        run: |
          python src/fetch_usaspending.py
          python src/enrich.py data/nih_top_recipients_last_90d.csv

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data/*.json || true
          git commit -m "chore: refresh USAspending data" || echo "No changes to commit"
          git push

      - name: Publish data for GitHub Pages
        run: |
          mkdir -p docs/data
          cp -f data/*.csv docs/data/ || true
          cp -f data/*.json docs/data/ || true
          touch docs/.nojekyll

      - name: Commit updated data & site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/* docs/.nojekyll || true
          git commit -m "chore: refresh data for GitHub Pages" || echo "No changes"
          git push
