title: NIH Awards Tracker
description: Contracts and recipients tracker (auto-updated)
# IMPORTANT: set your repo as baseurl so links work on Pages
baseurl: /nih-awards-tracker
url: https://feldmangn.github.io

# Use Hydejack (free/community)
remote_theme: qwtel/hydejack@v9.1.6

# Optional: show nav items
menu:
  - title: Dashboard
    url: /dashboard/
  - title: About
    url: /about/

# Plugins allowed on GitHub Pages
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Hydejack options (minimal)
hydejack:
  dark_mode: auto
  no_breadcrumbs: true
  no_drawer: false
